sudo: required
services:
  - docker

before_install:
  - docker build -t akshatav56/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true akshatav56/docker-react npm run test

language: generic

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-382669431520"
  bucket_path: "docker-react"
